local:
  service: Disk
  root: <%= ENV.fetch("DATA_PATH", Rails.root.join("storage")) %>/files/private

public_local:
  service: Disk
  root: <%= ENV.fetch("DATA_PATH", Rails.root.join("storage")) %>/files/public
  public: true
